export const Vals = [
    {
        id:1,
        title:"art 1",
        bg_img:'',
        items:[
            {title:"art 1",img:''},
            {title:"art 1",img:''},
            {title:"art 1",img:''},
        ],
        desc:'desc',
    },
    {
        id:2,
        title:"art 2",
        items:[
            {title:"art 2",img:''},
            {title:"art 2",img:''},
            {title:"art 2",img:''},
        ],
        desc:'desc',
        bg_img:'',
        img1:'',
        img2:'',
        img3:'',
    },
    {
        id:3,
        title:"art 3",
        items:[
            {title:"art 3",img:''},
            {title:"art 3",img:''},
            {title:"art 3",img:''},
        ],
        desc:'desc',
        bg_img:'',
        img1:'',
        img2:'',
        img3:'',
    },
    {
        id:4,
        title:"art 4",
        items:[
            {title:"art 4",img:''},
            {title:"art 4",img:''},
            {title:"art 4",img:''},
        ],
        desc:'desc',
        bg_img:'',
        img1:'',
        img2:'',
        img3:'',
    },
    {
        id:5,
        title:"art 5",
        items:[
            {title:"art 5",img:''},
            {title:"art 5",img:''},
            {title:"art 5",img:''},
        ],
        desc:'desc',
        bg_img:'',
        img1:'',
        img2:'',
        img3:'',
    },
    {
        id:6,
        title:"art 6",
        items:[
            {title:"art 6",img:''},
            {title:"art 6",img:''},
            {title:"art 6",img:''},
        ],
        desc:'desc',
        bg_img:'',
        img1:'',
        img2:'',
        img3:'',
    },
    {
        id:7,
        title:"art 7",
        items:[
            {title:"art 7",img:''},
            {title:"art 7",img:''},
            {title:"art 7",img:''},
        ],
        desc:'desc',
        bg_img:'',
        img1:'',
        img2:'',
        img3:'',
    },
    {
        id:8,
        title:"art 8",
        items:[
            {title:"art 8",img:''},
            {title:"art 8",img:''},
            {title:"art 8",img:''},
        ],
        desc:'desc',
        bg_img:'',
        img1:'',
        img2:'',
        img3:'',
    },
    {
        id:9,
        title:"art 9",
        items:[
            {title:"art 9",img:''},
            {title:"art 9",img:''},
            {title:"art 9",img:''},
        ],
        desc:'desc',
        bg_img:'',
        img1:'',
        img2:'',
        img3:'',
    },
]